[package]
name = "xee-ir"
version = "0.1.5"
edition = "2021"
authors = ["The Xee Project Developers"]
keywords = ["xml", "xpath", "xslt"]
categories = ["text-processing", "compilers"]
license = "MIT"
description = "Xee intermediate representation and compilation to bytecode"
repository = "https://github.com/Paligo/xee"
readme = "README.md"
documentation = "https://docs.rs/xee-ir"
homepage = "https://github.com/Paligo/xee"

[features]
serde = [
    "dep:serde",
    "dep:rmp-serde",
    "xee-xpath-ast/serde",
    "xee-schema-type/serde",
    "xee-interpreter/serde",
    "ordered-float/serde",
    "ibig/serde",
    "rust_decimal/serde-with-str",
    "iri-string/serde",
    "xot/serde",
    "ahash/serde",
]

[dependencies]
xee-xpath-ast = { path = "../xee-xpath-ast", version = "0.1.4" }
xee-schema-type = { path = "../xee-schema-type", version = "0.1.4" }
xee-interpreter = { path = "../xee-interpreter", version = "0.2.0" }
serde = { workspace = true, features = ["derive"], optional = true }
rmp-serde = { version = "1", optional = true }
ahash = { workspace = true }
ordered-float = { workspace = true }
iri-string = { workspace = true }
rust_decimal = { workspace = true }
ibig = { workspace = true }
xot = { workspace = true }


[dev-dependencies]
insta = { workspace = true, features = ["yaml", "glob"] }
